- name: Playbook Reproducer
  hosts: all
  gather_facts: false

  vars:
  
    # $ python
    # Python 3.11.7 (main, Dec 18 2023, 00:00:00) [GCC 13.2.1 20231011 (Red Hat 13.2.1-4)] on linux
    # Type "help", "copyright", "credits" or "license" for more information.
    # >>> print(['- {}'.format(i) for i in 'abcdefghijklmnopqrstuvwxyz'])
    # ['- a', '- b', '- c', '- d', '- e', '- f', '- g', '- h', '- i', '- j', '- k', '- l', '- m', '- n', '- o', '- p', '- q', '- r', '- s', '- t', '- u', '- v', '- w', '- x', '- y', '- z']
    # >>> for x in ['- {}'.format(i) for i in 'abcdefghijklmnopqrstuvwxyz']: print(x)

    #  for i in {1..650}; do echo -e "      - $i"; done > multiplevars2.txt
    services:


    #  for i in {1..650}; do echo -e "      - name: $i\n$(for i in {1..650}; do echo -e "        var$i: $i"; done)"; done > multiplevars.txt
    pools:
    
    pools_pre: []

  tasks:
    - name: Loop set_fact
      ansible.builtin.set_fact:
        pools_pre: "{{ pools_pre + [ item[1] ] }}"
      when: item[0] == item[1].name
      with_nested:
        - "{{ services }}"
        - "{{ pools }}"
      delegate_to: localhost

    - debug: var=pools_pre
